image: Ubuntu

branches:
  only:
    - master

build: off


install:

  - ps:
  - java -jar ./artifacts/app-card-delivery.jar &

build_script:
  - ps: chmod +x gradlew
  - ps: ./gradlew test --info "-Dselenide.headless=true"