image: Ubuntu

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки


install:

  - ps:
  - java -jar ./artifacts/app-card-delivery.jar &

build_script:
  - ps: ./gradlew test --info "-Dselenide.headless=true"  # стартуем Selenide в Headless-режиме (см.ниже)

on_finish:
  - ps: Stop-Process -Id $App.Id  # оставливаем SUT